/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

export function Robo(props) {
  const shapeContainer = useRef(null);
  const shperesContainer = useRef(null);
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/leela-1117.glb');
  const { actions } = useAnimations(animations, group)

  useGSAP (() => {
    const tl = gsap.timeline();
    tl.from(shapeContainer.current.position, {
        y:5,
        duration: 3,
        ease:"circ.out"
    });
    tl.from(shperesContainer.current.rotation, {
        x:0,
        y:6,
        duration:20,
        ease: "power1.inOut",
    });
  })
  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group ref={shperesContainer} name="Scene">
        <group name="RobotArmature">
          <skinnedMesh
            name="Leela"
            geometry={nodes.Leela.geometry}
            material={materials.Leela_Texture}
            skeleton={nodes.Leela.skeleton}
          />
          <primitive object={nodes.Body} />
          <primitive object={nodes.FootL} />
          <primitive object={nodes.FootR} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/leela-1117.glb')